export interface Customer {    
    tel:string,
    name: string,
    title: string, 
    furigana: string,
    sortcode:string,
    serviceLevel:string,
    groupCode:string,
    address1: string,     
    address2: string,
    address3: string, 
    address4: string, 
    company:string,
    department:string,
    email: string,
    email1: string,
    email2: string,
    remarks: string,    
    customerFactor: string,
    clarificationCode: string,
    receipt: string,
};
