export interface Customer {    
    tel:string,
    name: string,
    title: string, 
    furigana: string,
    sortcode:string,
    search: string,
    serviceLevel:string,
    prefectures:string,
    groupCode:string,
    address1: string,     
    address2: string,
    address3: string, 
    address4: string, 
    company:string,
    department:string,
    email: string,
    email1: string,
    email2: string,
    remarks: string,    
    // blackInfo: string,
    // regionCode: string,
    // gender: string,
    // age: string,
    customerFactor: string,
    clarificationCode: string,
    // orderCategory: string,
    // classification: string,
    // lastStoreCd: string,
    // customerRank: string,
    // creditRegistration: string,
    // blackInfo: string,
    // blackInfo: string,
    // blackInfo: string,
    // blackInfo: string,
    // blackInfo: string,    
    receipt: string,
};
